server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lqinrui/springcloud-config.git
          search-paths:
            - springcloud-configp
          username: 15235151477@163.com
          password: jklm6516
      label: main              #分支
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
